Rewrite
Azure-Terraform/terraform-azurerm-kubernetes-aad-pod-identity pull request #2
Opened 2021-02-22 14:11 UTC by dutsmiller

Significant changes
- Update to helm chart 3.x

2021-03-16 16:25 UTC, b-odonoghue commented on variables.tf
> +variable "intstall_crds" {
@dutsmiller this should be `install_crds` vs `int`stall_crds

2021-03-16 16:26 UTC, b-odonoghue commented on variables.tf
> +variable "intstall_crds" {
I have added a commit to fix this

2021-03-29 20:14 UTC, fabiendelpierre requested changes

2021-03-29 20:14 UTC, fabiendelpierre commented on providers.tf
> +    helm = ">= 2.0.0"
Please update this to TF 0.14 syntax (with the added `source` argument).

2021-03-29 20:14 UTC, fabiendelpierre commented on variables.tf
> +  description = "Enable feature when AKS cluster is uses Kubenet for CNI, leave default if use AzureCNI"
Grammar fix? 😄

2021-03-29 20:14 UTC, fabiendelpierre commented on variables.tf
> +  description = "Azure identites to be configured"
Fix spelling of "identities"

2021-03-30 20:21 UTC, fabiendelpierre approved these changes

2021-03-30 20:32 UTC, merged